/* ============================================================
   Maestro's Gambit — facts.js
   A pool of concise, accurate "did you know?" orchestral facts
   shown while a player waits for the relay/opponent to connect.
   Original phrasings; facts themselves are not copyrightable.
   MG.ORCH_FACTS is consumed by ui.js (the connecting panel).
   ============================================================ */
(function () {
  const MG = (globalThis.MG = globalThis.MG || {});

  MG.ORCH_FACTS = [
    'The modern symphony orchestra seats roughly 80–100 musicians in four families: strings, woodwinds, brass, and percussion.',
    'The violin has four strings tuned in perfect fifths — G, D, A, and E.',
    'A concert harp has 47 strings and seven pedals, each able to sharpen or flatten a note.',
    'The double bass is the largest and lowest-pitched string instrument in the standard orchestra.',
    'The word "orchestra" comes from the Greek for the semicircular space where the chorus danced in ancient theatres.',
    'The concertmaster is the principal first violinist, who tunes the orchestra and sits nearest the conductor.',
    'Before a concert the oboe sounds an "A" because its reedy tone is easy for everyone to tune to.',
    'The timpani, or kettledrums, can be tuned to exact pitches using a foot pedal.',
    'A piccolo plays an octave higher than the flute and is the highest-pitched orchestral instrument.',
    'The clarinet was invented around 1700 by Johann Christoph Denner in Germany.',
    'Antonio Stradivari built violins in Cremona, Italy; surviving "Strads" can sell for millions.',
    "The French horn's tubing, if unwound, would stretch about 12 to 13 feet.",
    'A trombone changes pitch with a sliding tube rather than valves or keys.',
    'The celesta, a keyboard that strikes metal bars, gives "Dance of the Sugar Plum Fairy" its bell-like sound.',
    'Beethoven completed his Ninth Symphony in 1824, after he had gone almost completely deaf.',
    "The 'Ode to Joy' from Beethoven's Ninth is the anthem of the European Union.",
    "Vivaldi's 'The Four Seasons' (c. 1725) is early program music, each concerto depicting a season.",
    'A standard piano has 88 keys: 52 white and 36 black.',
    'Mozart wrote his first symphony at the age of eight.',
    'The conductor\'s baton became common only in the 1800s; earlier leaders kept time with a bow or a staff.',
    'The bassoon is a double-reed instrument whose tube is over eight feet long, folded in half.',
    '"Fortissimo" (ff) means very loud, while "pianissimo" (pp) means very soft.',
    'The cello is played seated, held between the knees, resting on a spike called an endpin.',
    "Tchaikovsky's '1812 Overture' scores real cannon fire in its finale.",
    'The glockenspiel uses tuned metal bars and sounds two octaves higher than it is written.',
    "An orchestra's strings are usually seated in an arc directly in front of the conductor.",
    'The viola is slightly larger than the violin and is read in the alto clef.',
    "Gustav Holst's suite 'The Planets' has seven movements but leaves out Earth.",
    'A "symphony" is typically a large work in several movements for full orchestra.',
    "The trumpet is one of the oldest instruments; metal examples were found in Tutankhamun's tomb.",
    'Johann Sebastian Bach had 20 children, and many of them became musicians.',
    'The English horn is neither English nor a horn — it is an alto oboe.',
    "Ravel's 'Boléro' repeats a single melody for about 15 minutes as the orchestration swells.",
    'A "concerto" sets a solo instrument against the full orchestra.',
    'The tuba, added to orchestras in the 1830s, is the lowest brass instrument.',
    "Wagner's 'Ride of the Valkyries' comes from his opera 'Die Walküre.'",
    'The harpsichord plucks its strings, while the piano strikes them with hammers.',
    'A pizzicato passage is played by plucking string instruments with the fingers.',
    "Ravel orchestrated Mussorgsky's piano suite 'Pictures at an Exhibition' in 1922.",
    'The snare drum buzzes thanks to metal wires (snares) stretched across its bottom head.',
    "Handel's 'Messiah,' with its 'Hallelujah' chorus, was composed in just 24 days in 1741.",
    '"A cappella" means singing without any instrumental accompaniment.',
    'The flute is metal today but is a woodwind because it was once made of wood.',
    "Dvořák wrote his 'New World' Symphony while living in the United States in 1893.",
    'The marimba has wooden bars and resonator tubes, giving it a warm, mellow tone.',
    'A "movement" is a self-contained section of a larger work like a symphony.',
    "The oboe's double reed is two thin blades of cane that vibrate against each other.",
    "Stravinsky's 'The Rite of Spring' caused a near-riot at its 1913 Paris premiere.",
    '"Crescendo" means gradually louder; "diminuendo" means gradually softer.',
    'The contrabassoon plays an octave below the bassoon, reaching the orchestra\'s lowest notes.',
    'A "sonata" is usually a piece for one or two instruments in several movements.',
    'Cymbals are among the oldest percussion instruments, dating back thousands of years.',
    'Haydn is often called the "Father of the Symphony," having written over 100 of them.',
    'A mute is a device inserted into a brass bell to soften or color the sound.',
    "Smetana composed his suite 'Má vlast,' including 'The Moldau,' while completely deaf.",
    'Harpists pluck with the fingers — but never with the little finger.',
    "Prokofiev's 'Peter and the Wolf' gives each character its own instrument as a voice.",
    'The triangle, though tiny, can be heard clearly over a full orchestra.',
    'A "fugue" weaves a single melody through several overlapping voices.',
    'The saxophone, invented by Adolphe Sax around 1840, is rare in orchestras but common in bands.',
    "Mahler's Eighth Symphony is nicknamed the 'Symphony of a Thousand' for its huge forces.",
    'The violin bow is traditionally strung with horsehair, rubbed with rosin for grip.',
    '"Legato" means smooth and connected; "staccato" means short and detached.',
    'The xylophone has wooden bars and a brighter, harder tone than the marimba.',
    "Rimsky-Korsakov's 'Flight of the Bumblebee' is famous for its rapid chromatic runs.",
    "A grand piano's strings together pull with a tension of around 18 to 20 tons.",
    'The "downbeat" is the first, strongest beat of a measure — the conductor\'s hand falling.',
    "Schubert's Eighth Symphony has only two finished movements and is called the 'Unfinished.'",
    'The double bass can be played with either a German or a French bow grip.',
    "Copland's 'Fanfare for the Common Man' opens with brass and percussion alone.",
    '"Tempo" is the speed of the music; "allegro" is fast and "adagio" is slow.',
    'The pipe organ has been called the "King of Instruments" for its size and range.',
    "Berlioz's 'Symphonie fantastique' (1830) tells a tale of obsessive love in five movements.",
    "A harp's pedals can shift every string of one note name at once.",
    'A "chord" is three or more notes sounded together.',
    'The clarinet family ranges from the tiny E-flat clarinet to the large bass clarinet.',
    "Grieg's 'In the Hall of the Mountain King' speeds up and grows to a frantic finish.",
    "Brass instruments make their sound from the player's buzzing lips, not a reed.",
    '"Rubato" is a flexible stretching of the tempo for expressive effect.',
    "The orchestra warms up freely until the concertmaster signals the tuning 'A.'",
    "Pachelbel's 'Canon in D' repeats the same bass line from start to finish.",
    'The percussion section is sometimes nicknamed the "kitchen" of the orchestra.',
    "Bizet's 'Carmen' flopped at its 1875 premiere, then became a beloved opera.",
    'The string section is the largest group in the orchestra, often over 60 players.',
    '"Forte" means loud, from the Italian word for strong.',
    "Saint-Saëns's 'The Carnival of the Animals' paints creatures from swans to elephants.",
    'A "rest" is a notated silence — as vital to the music as any note.',
    'A horn player keeps a hand inside the bell to fine-tune pitch and tone.',
    "Gershwin's 'Rhapsody in Blue' opens with a famous swooping clarinet glissando.",
    'The concert-pitch standard "A" is usually 440 Hz, though some orchestras tune a touch higher.',
    'The bass drum is the largest drum in the orchestra and has no fixed pitch.',
    "Elgar's 'Pomp and Circumstance' March No. 1 is heard at graduations worldwide.",
    'A "key signature" tells players which sharps or flats to use throughout a piece.',
    'The viola usually plays the inner harmonies that bind the string section together.',
    "Holst gave each planet a character, from warlike Mars to the mystic Neptune.",
    'The "coda" is a closing passage that brings a piece to its end.',
    "A trumpet's three valves route air through extra tubing to change the pitch.",
    "Debussy's 'Clair de Lune' takes its name from a poem by Paul Verlaine.",
    'An "octave" spans eight notes; the top note vibrates twice as fast as the bottom.',
    'A piece often ends on the "tonic" — the home note that feels most at rest.',
  ];
})();
